### ISSUE TITLE
Will this project be open source

### ISSUE THREAD

**Issue by Jessy-Huang** [Pointcept/OpenIns3D#1]
Hello, your work is great and I am very interested in your project. Will this project be open source. Or can I contact you privately? My QQ number is 3166548848

**Comment by ZheningHuang** [comment]
Hi, thanks for your interest in our work. Yes, the code and pre-trained models will be released later this year.

Best,
Zhening

**Comment by ZheningHuang** [comment]
Hi happy new year and we have released the code! feel free to check it out!
