### ISSUE TITLE
how to make the gif result

### ISSUE THREAD

**Issue by 123lcy123** [Pointcept/OpenIns3D#15]
This is a great work. I have tried the Zero-Shot Inference you provided. Now I would like to ask how to make the gif result you showed in assets.Thank you!

**Comment by ZheningHuang** [comment]
Thank you for your interest in our work. The GIF was created using PowerPoint. I'm sure you could write a quick Python code to do it as well—just render one image with masks and one without.

Best regards,  
Zhening

**Comment by ZheningHuang** [comment]
close this for now and let me know if you have more issues.
