### ISSUE TITLE
ValueError: No mesh interpreter found to read ./data/s3dis/scenes/WC_1.npy.

### ISSUE THREAD

**Issue by JiachengDeng** [Pointcept/OpenIns3D#19]
This is an amazing work and a highly readable code repository. However, I encountered the following bug while running the training command on the S3DIS dataset. 

`Traceback (most recent call last):
  File "/ssd/djc/open-vocabulary/OpenIns3D/openins3d/main.py", line 270, in <module>
    openins3d = OpenIns3D(dataset_name.lower(), dataset_path, image_detector = args.detector, mode = args.task, use_2d = args.use_2d, vis = args.save_vis)
  File "/ssd/djc/open-vocabulary/OpenIns3D/openins3d/main.py", line 49, in __init__
    self.OV_instance_seg()
  File "/ssd/djc/open-vocabulary/OpenIns3D/openins3d/main.py", line 102, in OV_instance_seg
    self.snap.scene_image_rendering(scene_path, f"{scene}_vis", mode=["global"], mask=[pred_masks, pred_class_txt]) # Comment this out unless visualization is needed, as it is quite slow.
  File "/ssd/djc/open-vocabulary/OpenIns3D/openins3d/snap.py", line 238, in scene_image_rendering
    mesh = pt3d_io.load_mesh(scan_pc_raw, device=self.device)
  File "/data/djc/anaconda3/envs/openins3d/lib/python3.9/site-packages/pytorch3d/io/pluggable.py", line 138, in load_mesh
    raise ValueError(f"No mesh interpreter found to read {path}.")
ValueError: No mesh interpreter found to read ./data/s3dis/scenes/WC_1.npy.`

My PyTorch3D version is linux-64/pytorch3d-0.7.5-py39_cu116_pyt1131.tar.bz2. Could you please advise me on how to resolve this bug?

**Comment by ZheningHuang** [comment]
Hi,

Thank you for your interest in our work.

Apologies for the bug. I tested it myself and found that the issue was introduced in the save visualization code. I’ve fixed it and pushed the update. You can either pull from the `main` branch or manually update the file [here](https://github.com/Pointcept/OpenIns3D/blob/main/openins3d/main.py).

**Previously:**

```python
if self.save_vis:
    self.snap = Snap([800, 800], [3, 0.1, 1.0], f"{self.save_folder}")
    self.snap.scene_image_rendering(scene_path, f"{scene}_vis", mode=["global"], mask=[pred_masks, pred_class_txt]) 
```

**Now:**

```python
if self.save_vis:
    if pred_masks.shape[1] == 0:  # No mask in this scene
        continue
    if self.dataset_name == "replica" and use_2d:
        self.snap = Snap([800, 800], [3, 0.1, 1.0], f"{self.save_folder}")
    if self.dataset_name == 's3dis' or 'stpls3d':
        self.snap.scene_image_rendering(pcd_rgb, f"{scene}_vis", mode=["global"], mask=[pred_masks, pred_class_txt]) 
    else:
        self.snap.scene_image_rendering(scene_path, f"{scene}_vis", mode=["global"], mask=[pred_masks, pred_class_txt])
```


You can also set the `save_vis ` option to `False` to save time:

```bash
python openins3d/main.py --dataset s3dis --task OVIS --detector odise --save_vis False
```

Thanks again for reporting this issue. Please feel free to reach out if you have any questions while running the code.

Zhening

**Comment by JiachengDeng** [comment]
Hi Zhening,

Thank you very much for your prompt response and solution. My problem has been resolved according to your suggested modifications. I really appreciate your excellent work！

Thanks again.

Yours sincerely,
Jiacheng
