### ISSUE TITLE
About GT instance label of Replica dataset.

### ISSUE THREAD

**Issue by zhaihongjia** [Pointcept/OpenIns3D#22]
Hello, how do you obtain the point-level instance label of Replica datasets?
https://github.com/Pointcept/OpenIns3D/blob/main/scripts/prepare_replica.sh

**Comment by ZheningHuang** [comment]
Hi, Replica evaluation was first introduced in OpenMask3D, and the processed dataset was initially shared via email.

Reference: [OpenMask3D GitHub Issue #5](https://github.com/OpenMask3D/openmask3d/issues/5)
