### ISSUE TITLE
数据集mask的ground truth生成

### ISSUE THREAD

**Issue by tj12323** [Pointcept/OpenIns3D#23]
您好，想问一下提供的mask的ground truth是如何生成的呢？可以提供代码吗？

**Comment by ZheningHuang** [comment]
你好，这个是mask3D提出的格式，可以参考下他们的数据处理的方法.

具体在这里： https://github.com/JonasSchult/Mask3D/blob/11bd5ff94477ff7194e9a7c52e9fae54d73ac3b5/datasets/preprocessing/scannet_preprocessing.py#L204C13-L204C63

**Comment by tj12323** [comment]
好的，感谢！

**Comment by tj12323** [comment]
您好，很抱歉再次打扰您。
我完全按照 Mask3D 的处理方式生成了 txt 形式的 ground truth 文件，与预期结果一致。但是，在将这个 ground truth 转换为 mask/ground_truth/ 文件夹下的 .pt 文件时，结果和预期不符。
因此，我想请教一下，.pt 文件的具体生成过程是什么？是否有任何特定的步骤或转换规则需要特别注意？
非常感谢您的帮助！
