### ISSUE TITLE
我希望在自己的数据上进行测试，对数据有什么需求吗？

### ISSUE THREAD

**Issue by Novmaple** [Pointcept/OpenIns3D#25]
我使用了扫描仪扫描的pts数据，通过cloud compare软件转换成了ply格式，但是这样的数据并不能运行，程序会报错
利用的命令是
```
python zero_shot_multi_vocs.py --pcd_path data/demo_scenes/c1p.ply --detector yoloworld 
```
结果是
```
RuntimeError: vstack expects a non-empty TensorList
```
请问对数据的格式有什么要求吗？另外detector的种类和预训练权重可以替换以便在专业环境中进行测试吗？

**Comment by ZheningHuang** [comment]
hi，

ply 差别还挺大的，建议先把 xyz 和rgb 转化成 npy，然后用s3dis 的那个setting 来load。

input主要是xyz，和rgb的数据，如果这个提取出来的话，应该不会有什么问题！

**Comment by Novmaple** [comment]
谢谢！
