### ISSUE TITLE
mask/ground_truth/pt文件的生成

### ISSUE THREAD

**Issue by tj12323** [Pointcept/OpenIns3D#27]
您好，很抱歉再次打扰您。
我完全按照 Mask3D 的处理方式生成了 txt 形式的 ground truth 文件，与预期结果一致。但是，在将这个 ground truth 转换为 mask/ground_truth/ 文件夹下的 .pt 文件时，结果和预期不符。
因此，我想请教一下，.pt 文件的具体生成过程是什么？是否有任何特定的步骤或转换规则需要特别注意？
非常感谢您的帮助！

**Comment by ZheningHuang** [comment]
Hi，

mask/ground_truth/ 目录下的每个文件都是GT的mask。

这些GT的mask格式是 (point_number, mask_num)。

有几点需要注意：

为了节省存储空间，默认读取的是sparse tensor。所以如果你自己生成的话，需要先将它们转换为稀疏张量再保存。例如：
```
mask_sparse = mask.to_sparse()
torch.save(mask_sparse, "data/replica/masks/ground_truth/office0.pt")
```

有任何问题请随时提问！
