### ISSUE TITLE
Request for More Info on AP50 and AP25 Scores

### ISSUE THREAD

**Issue by PhucNDA** [Pointcept/OpenIns3D#3]
Hi there,

Thanks for significant work. We've been following your research closely and are eager to cite it in our own work.
To make our citation more informative, we were wondering if you could share additional details about the AP50 and AP25 scores of your method, particularly for the Base and Novel classes independently. Could you provide the evaluation log files from the experiments listed in Table 1 for ScannetV2 and S3DIS?

Thanks so much for your contributions.

Best,
PhucNDA

**Comment by ZheningHuang** [comment]
Hi PhucNDA,

Thanks for your patience.
I have emailed you the log files. We will also release more detailed log files for different testing schemes on this repository
very soon.

Best,
Zhening
