### ISSUE TITLE
Errors when following the README

### ISSUE THREAD

**Issue by hithqd** [Pointcept/OpenIns3D#4]
Hi, when I follow the README and run the scannet test, the following error comes out. How can I solve it?

<img width="1671" alt="image" src="https://github.com/Pointcept/OpenIns3D/assets/37433515/1d7e1b70-5feb-4458-be4e-5cb576689406">

**Comment by ZheningHuang** [comment]
Hi, thanks for being interested in our work. This happened because I believe the version of OmegaConf is not right. Please try:
```
pip install omegaconf==2.1.1
```
let me know if this solved your problem.

Best,
Zhening

**Comment by hithqd** [comment]
It does not work either.

**Comment by ZheningHuang** [comment]
I have just added an environment YAML file. Please take a look in the version control and see what the differences are. I am sure that this error message can be resolved by using the correct version of `omegaconf`. So, perhaps you could try different versions of `omegaconf` that fits your installation to see if this problem persists?

Do let me know if this is helpful.

Zhening

**Comment by ZheningHuang** [comment]
Hi, I have updated a major revision of the code, and this issue should be fine now. It occurred because the mask proposal module, which is built upon mask3d, used an old version of Hydra, while Detectron2 requires a newer version. I have made slight changes to the code, so it should do the job now. 

Zhening

**Comment by ZheningHuang** [comment]
Close this issue now due to inaction. Please feel free to reopen it if you encounter this again.

Zhening
