### ISSUE TITLE
How to train class-agnostic Mask3D with Mask Filtering and Mask Scoring module?

### ISSUE THREAD

**Issue by yxchng** [Pointcept/OpenIns3D#5]

**Comment by ZheningHuang** [comment]
Hi, thank you for your interest in our work. (Apologies for the super delay in response; I've just returned from a break.

The class-agnostic Mask3D is trained by modifying the following:

1) Removing the classification loss and adding IOU loss.
2) Removing the class label in Hungarian matching.

For training, please navigate to this [folder](https://github.com/Pointcept/OpenIns3D/tree/main/openins3d/mask3d) and use this [config](https://github.com/Pointcept/OpenIns3D/blob/main/openins3d/mask3d/conf/config_base_instance_segmentation_ca.yaml) file:

We suggest also referring to [Mask3D](https://github.com/JonasSchult/Mask3D) for more information on data processing as well as environment setup. They have more comprehensive instructions there on how to train Mask3D. We adopted the [easy setup](https://github.com/cvg/Mask3D) for quick inference.

**Comment by ZheningHuang** [comment]
I am closing this for now. Mask proposal is always a bottleneck for 3D open-world instance segmentation. Recent work, such as [Segment3D](https://segment3d.github.io/), may provide a better solution for mask proposal, which we will also look into in the future.

Best,
Zhening
