### ISSUE TITLE
build lookup dict failes

### ISSUE THREAD

**Issue by rolfstarke** [Pointcept/OpenIns3D#7]
Dear Developers,

i am able to reproduce your examples, but when i run the zero_shot.py it appears to fail to build the lookup dictionaries. i changed this `sys.path.append("/home/zelda/zh340/myzone/lookup/ODISE")` within the build_lookup_dict.py to my local ODISE folder, but i cannot resolve the issue. any help would be appreciated.

![image](https://github.com/Pointcept/OpenIns3D/assets/15931647/4397ca39-51fb-422e-bc38-3301ed0a784a)

**Comment by ZheningHuang** [comment]
Hi,

If you managed to generate some results as you posted in the previous issue, that means ODISE is working okay at the time of the test.

From this screenshot, it seems that the build lookup direction is working fine.

You can also check your generated folder to see if you have ODISE results saved.

Let me know if you still encounter any problems.

Best regards,
Zhening

**Comment by rolfstarke** [comment]
you're right, the ODISE results are saved. sorry

**Comment by rolfstarke** [comment]
you're right, the ODISE results are saved. sorry
